name: github-action-tools-workspace
repository: https://github.com/dart-action/tools

packages:
  - packages/**

scripts:
  analyze:
    exec: dart analyze .
  get:
    exec: flutter pub get
  test:
    exec: flutter test
  format:
    exec: dart format --set-exit-if-changed .
  cp_files:
    exec: cp ../../LICENSE . && cp ../../.markdownlint.jsonc .

sdkPath: auto

command:
  version:
    releaseUrl: true
