name: github-action-tools-workspace
repository: https://github.com/dart-action/tools

packages:
  - packages/**

scripts:
  analyze:
    exec: dart analyze .
  get:
    exec: flutter pub get
  test:
    exec: flutter test
  format:
    exec: dart format --set-exit-if-changed .
  init:
    exec: cp ../../LICENSE . && cp ../../.markdownlint.jsonc . && cp ../../index_generator.yaml . && dart pub add dev:index_generator:^3.4.0 && dart pub get
  cp_files:
    exec: cp ../../LICENSE . && cp ../../.markdownlint.jsonc . && cp ../../index_generator.yaml .
  index_file:
    exec: dart run index_generator:index_generator
sdkPath: auto

command:
  version:
    releaseUrl: true
