name: flutter_image_compress
repository: https://github.com/fluttercandies/flutter_image_compress

packages:
  - packages/**

scripts:
  analyze:
    exec: dart analyze .
  get:
    exec: flutter pub get
  test:
    exec: flutter test
  format:
    exec: dart format --set-exit-if-changed .
  cp_files:
    exec: cp ../../LICENSE . && cp ../../.markdownlint.jsonc .

sdkPath: auto

command:
  version:
    releaseUrl: true
